import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Link from "next/link";
import { ChevronLeft, ArrowRight, Calculator, TrendingUp, Search, Percent, HelpCircle, Landmark } from "lucide-react";
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: "Professional Valuation: Mastering EV/EBITDA and FCF Yield",
    description: "Beyond P/E ratios. A sophisticated deep-dive into Enterprise Value, Cash Flow Yields, and the metrics used by institutional analysts in India.",
};

export default function ProfessionalValuationGuide() {
    return (
        <main className="min-h-screen bg-white">
            <Navbar />

            {/* SEO Hero Section */}
            <section className="relative pt-32 md:pt-48 pb-20 bg-accent-cream border-b border-orange-100/50 overflow-hidden">
                <div className="absolute top-0 right-0 w-1/2 h-full bg-gradient-to-l from-orange-100/40 to-transparent pointer-events-none"></div>
                <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
                    <Link
                        href="/learn"
                        className="inline-flex items-center gap-2 text-primary font-bold mb-8 hover:gap-3 transition-all"
                    >
                        <ChevronLeft size={20} />
                        Back to Knowledge Center
                    </Link>

                    <h1 className="text-4xl md:text-6xl font-serif font-bold text-slate-900 mb-8 leading-tight">
                        <span className="text-primary">Professional</span> Valuation: <br />
                        Decoding EV & Cash Flow
                    </h1>

                    <p className="text-xl md:text-2xl text-slate-600 font-medium leading-relaxed max-w-3xl mb-12">
                        Institutional capital doesn't look at P/E ratios. They look at the cost to own the entire business and the actual cash it produces. Welcome to the professional-grade valuation toolkit.
                    </p>

                    <div className="flex flex-wrap gap-4">
                        <span className="bg-white/80 backdrop-blur px-4 py-2 rounded-full border border-orange-100 text-slate-500 text-sm font-bold uppercase tracking-wider">Reading Time: 15 Mins</span>
                        <span className="bg-white/80 backdrop-blur px-4 py-2 rounded-full border border-orange-100 text-slate-500 text-sm font-bold uppercase tracking-wider">Concept: Quantitative Valuation</span>
                        <span className="bg-white/80 backdrop-blur px-4 py-2 rounded-full border border-orange-100 text-slate-500 text-sm font-bold uppercase tracking-wider">Target: Sophisticated Analysts</span>
                    </div>
                </div>
            </section>

            {/* Article Content */}
            <article className="py-20 max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
                <div className="prose prose-lg prose-slate max-w-none">
                    <p className="lead text-2xl text-slate-900 font-serif mb-16 border-l-4 border-primary pl-8">
                        "EBITDA is a pre-tax, pre-interest metric. It tells you about the raw power of the engine. Enterprise Value tells you the total cost of the car. P/E only tells you the cost of the monthly payment."
                    </p>

                    <h2 className="text-3xl font-serif font-bold text-slate-900 mt-16 mb-8">Introduction: The P/E Blindspot</h2>
                    <p>
                        The Price-to-Earnings (P/E) ratio is the most quoted metric in retail finance because it is easy to calculate. But for an HNI managing ₹50L+ portfolio, P/E has a massive blindspot: it completely ignores <strong>Debt</strong>. A company with ₹10,000Cr in debt and another with ₹10,000Cr in cash can have the same P/E, but their true values are billions of rupees apart.
                    </p>
                    <p>
                        Professional analysts use **Enterprise Value (EV)** and **Free Cash Flow (FCF)** as the primary filters for valuation. This guide provides the institutional-grade definitions and applications for these metrics in the Indian context.
                    </p>

                    <h2 className="text-3xl font-serif font-bold text-slate-900 mt-16 mb-8">Metric 1: EV/EBITDA – The Real Multiplier</h2>
                    <p>
                        <strong>Enterprise Value (EV)</strong> is the theoretical "takeover price" of a company. It is calculated as: <br />
                        <span className="block my-4 p-4 bg-slate-100 border-l-4 border-primary font-mono text-center">EV = Market Cap + Total Debt - Cash & Equivalents</span>
                    </p>
                    <p>
                        <strong>EBITDA</strong> (Earnings Before Interest, Taxes, Depreciation, and Amortization) represents the raw operating profit generated by the business.
                    </p>
                    <p>
                        <strong>Why we use EV/EBITDA:</strong> It allows us to compare companies with different capital structures. It is especially critical in India's industrial and manufacturing sectors (e.g., our "China+1" themes) where depreciation and interest costs can vary wildly between old-school factories and new-age tech-led plants.
                    </p>

                    <h2 className="text-3xl font-serif font-bold text-slate-900 mt-16 mb-8">Metric 2: Free Cash Flow (FCF) Yield</h2>
                    <p>
                        Net Profit is an accounting opinion; Cash is a fact. <strong>Free Cash Flow</strong> is the cash left over after the business has paid its operating expenses and all its necessary Capex (Capital Expenditure).
                    </p>
                    <p>
                        <strong>FCF Yield</strong> is calculated as: <br />
                        <span className="block my-4 p-4 bg-slate-900 text-white rounded-xl font-mono text-center">FCF Yield = Free Cash Flow / Enterprise Value</span>
                    </p>
                    <p>
                        At Tiger Assets, we look for an FCF Yield that is higher than the prevailing 10-year G-Sec yield. <strong>If a company is generating 8% FCF yield while the government pays 7.2%, you are being paid a premium to own the business.</strong>
                    </p>

                    <h2 className="text-3xl font-serif font-bold text-slate-900 mt-16 mb-8">Strategic Importance for India's ₹1Cr+ Portfolios</h2>
                    <div className="grid md:grid-cols-2 gap-8 my-12">
                        <div className="bg-white p-8 rounded-2xl border border-slate-200 shadow-sm">
                            < TrendingUp className="text-primary mb-4" size={32} />
                            <h4 className="text-xl font-bold text-slate-900 mb-2">Identifying Value Traps</h4>
                            <p className="text-base text-slate-600">A company might have a "cheap" P/E of 8, but if it has massive debt and negative FCF, it is a high-risk trap. EV-based metrics expose this instantly.</p>
                        </div>
                        <div className="bg-white p-8 rounded-2xl border border-slate-200 shadow-sm">
                            < Landmark className="text-primary mb-4" size={32} />
                            <h4 className="text-xl font-bold text-slate-900 mb-2">Asset Intensity Filter</h4>
                            <p className="text-base text-slate-600">By comparing EBITDA to FCF, we can see how "Asset Intensive" a business is. We prefer companies that can grow without needing to build a new factory every year.</p>
                        </div>
                    </div>

                    <h2 className="text-3xl font-serif font-bold text-slate-900 mt-16 mb-8">Practical Application: The SME vs. Large Cap Audit</h2>

                    <div className="space-y-12 my-12">
                        <div className="border border-slate-200 rounded-3xl p-8 shadow-sm">
                            <h3 className="text-2xl font-bold text-slate-900 mb-4 flex items-center gap-3">
                                <span className="text-primary">Scenario:</span> The Capital-Efficient Manufacturer
                            </h3>
                            <p>An SME company has a Market Cap of ₹1000Cr and ₹200Cr in cash. Its P/E is 20. <br />First-order look: "A bit expensive." <br />Professional look: Its EV is only ₹800Cr. Its EV/EBITDA is 10x. **Conclusion:** It is actually undervalued compared to its large-cap peers trading at 18x EV/EBITDA.</p>
                        </div>

                        <div className="border border-slate-200 rounded-3xl p-8 shadow-sm bg-orange-50/50 border-none relative overflow-hidden">
                            <h3 className="text-2xl font-bold mb-4 flex items-center gap-3 text-slate-900">
                                <span className="text-primary">Scenario:</span> The Negative FCF "Growth" Star
                            </h3>
                            <p className="text-slate-700">A new-age platform company is growing 50% y-o-y but has negative Free Cash Flow. **Reality Check:** This company is consuming your equity or taking on debt to buy its growth. Without a path to positive FCF Yield, it is a speculative bet, not a compounding asset.</p>
                        </div>
                    </div>

                    <h2 className="text-3xl font-serif font-bold text-slate-900 mt-16 mb-8">What sophisticated investors get wrong</h2>
                    <ul className="space-y-4 text-slate-700">
                        <li><strong>Mistaking EBITDA for Cash:</strong> "EBITDA is bullshit"Charlie Munger. EBITDA does not include interest on debt or the cost of replacing factories (depreciation). It must always be used *with* FCF, never in isolation.</li>
                        <li><strong>Comparing Across Industries:</strong> Comparing the EV/EBITDA of a software company (high margin, low asset) to a steel mill (low margin, high asset). Metrics must be used relative to industry benchmarks.</li>
                        <li><strong>Ignoring the "Maintenance Capex":</strong> Not all Capex is for growth. Some is just to keep the old machines running. A quality business should have plenty of FCF *after* replacing its machines.</li>
                    </ul>

                    <h2 className="text-3xl font-serif font-bold text-slate-900 mt-16 mb-8">Advisor’s Perspective</h2>
                    <p>
                        At Tiger Assets, we don't buy "stocks"; we buy **Cash-Generative Machines**. Our <strong>TIGER Framework</strong> uses proprietary adjustments to reported earnings to find the "True EBITDA" of a company. When we recommend an allocation in the <strong>SRE Tiger PMS</strong>, it is always because the EV-to-FCF math makes structural sense for a ₹1Cr+ mandate.
                    </p>

                    <div className="bg-slate-50 p-10 rounded-[40px] border border-slate-200 my-16">
                        <h3 className="text-2xl font-bold text-slate-900 mb-6 flex items-center gap-3">
                            < Search className="text-primary" />
                            The Valuation Audit Checklist
                        </h3>
                        <ul className="space-y-6 text-slate-800">
                            <li className="flex gap-4">
                                <div className="bg-white w-8 h-8 rounded-full border border-slate-200 flex items-center justify-center font-bold text-primary shrink-0">1</div>
                                <span className="font-medium">Calculate the <strong>Enterprise Value</strong> on your smartphone. (Market Cap + Debt - Cash).</span>
                            </li>
                            <li className="flex gap-4">
                                <div className="bg-white w-8 h-8 rounded-full border border-slate-200 flex items-center justify-center font-bold text-primary shrink-0">2</div>
                                <span className="font-medium">Has the company generated <strong>positive Free Cash Flow</strong> in 4 out of the last 5 years?</span>
                            </li>
                            <li className="flex gap-4">
                                <div className="bg-white w-8 h-8 rounded-full border border-slate-200 flex items-center justify-center font-bold text-primary shrink-0">3</div>
                                <span className="font-medium">Is the <strong>FCF Yield</strong> higher than the current 10-year G-Sec rate?</span>
                            </li>
                        </ul>
                    </div>

                    <h2 className="text-3xl font-serif font-bold text-slate-900 mt-16 mb-8 flex items-center gap-3">
                        <HelpCircle className="text-primary" size={32} />
                        Frequently Asked Questions
                    </h2>
                    <div className="space-y-8 divide-y divide-slate-100">
                        <div className="pt-8">
                            <h4 className="text-lg font-bold text-slate-900 mb-3">Does high debt automatically mean a bad EV/EBITDA?</h4>
                            <p className="text-slate-600">Not necessarily. It just means the *cost* of owning the entire business is higher. If the company generates massive EBITDA to cover the debt easily, it can still be a great purchase. EV just makes sure you don't forget about the debt.</p>
                        </div>
                        <div className="pt-8">
                            <h4 className="text-lg font-bold text-slate-900 mb-3">Which is better: Low P/E or High FCF Yield?</h4>
                            <p className="text-slate-600">High FCF Yield is always superior. A low P/E can be due to accounting tricks; a high FCF yield means the money is actually in the bank.</p>
                        </div>
                    </div>
                </div>

                {/* Internal Links CTA */}
                <div className="mt-20 p-12 bg-slate-950 text-white rounded-3xl text-center relative overflow-hidden shadow-2xl">
                    <div className="absolute top-0 right-0 w-96 h-96 bg-primary/20 rounded-full blur-[100px]"></div>
                    <h3 className="text-2xl font-bold mb-4 relative z-10 font-serif">Valuation is the price of admission.</h3>
                    <p className="text-slate-400 mb-8 max-w-2xl mx-auto relative z-10 text-lg">Use our analytical depth to identify the true cash-generators in the Indian market. Explore the SRE Tiger PMS valuation methodology.</p>
                    <div className="flex flex-wrap justify-center gap-4 relative z-10">
                        <Link href="/framework">
                            <button className="bg-primary text-white px-10 py-4 rounded-full font-bold hover:bg-primary-dark transition-all">Our Strategic Framework</button>
                        </Link>
                        <Link href="/products/sre-tiger-pms">
                            <button className="bg-white/10 text-white border border-white/20 px-10 py-4 rounded-full font-bold hover:bg-white/20 transition-all uppercase tracking-widest text-xs">Explore Tiger PMS</button>
                        </Link>
                    </div>
                </div>
            </article>

            <Footer />
        </main>
    );
}
