import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Link from "next/link";
import { ChevronLeft, ArrowRight, TrendingUp, SearchCheck, Target, BarChart3, HelpCircle, Trophy } from "lucide-react";
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: "Indexing vs. Active Alpha: The Professional Choice for India",
    description: "Why the US indexing model doesn't apply to India. A high-authority guide for ₹50L+ investors on identifying the sources of outperformance in Indian markets.",
};

export default function IndexingAlphaGuide() {
    return (
        <main className="min-h-screen bg-white">
            <Navbar />

            {/* SEO Hero Section */}
            <section className="relative pt-32 md:pt-48 pb-20 bg-accent-cream border-b border-orange-100/50 overflow-hidden">
                <div className="absolute top-0 right-0 w-1/2 h-full bg-gradient-to-l from-orange-100/40 to-transparent pointer-events-none"></div>
                <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
                    <Link
                        href="/learn"
                        className="inline-flex items-center gap-2 text-primary font-bold mb-8 hover:gap-3 transition-all"
                    >
                        <ChevronLeft size={20} />
                        Back to Knowledge Center
                    </Link>

                    <h1 className="text-4xl md:text-6xl font-serif font-bold text-slate-900 mb-8 leading-tight">
                        <span className="text-primary">Active Alpha</span> vs. Indexing: <br />
                        The India Reality
                    </h1>

                    <p className="text-xl md:text-2xl text-slate-600 font-medium leading-relaxed max-w-3xl mb-12">
                        Passive investing is touted as the "future," but in the inefficient, high-growth Indian market, index funds are often high-conviction paths to mediocrity.
                    </p>

                    <div className="flex flex-wrap gap-4">
                        <span className="bg-white/80 backdrop-blur px-4 py-2 rounded-full border border-orange-100 text-slate-500 text-sm font-bold uppercase tracking-wider">Reading Time: 13 Mins</span>
                        <span className="bg-white/80 backdrop-blur px-4 py-2 rounded-full border border-orange-100 text-slate-500 text-sm font-bold uppercase tracking-wider">Theme: Strategy Selection</span>
                        <span className="bg-white/80 backdrop-blur px-4 py-2 rounded-full border border-orange-100 text-slate-500 text-sm font-bold uppercase tracking-wider">Target: Growth Mandates</span>
                    </div>
                </div>
            </section>

            {/* Article Content */}
            <article className="py-20 max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
                <div className="prose prose-lg prose-slate max-w-none">
                    <p className="lead text-2xl text-slate-900 font-serif mb-16 border-l-4 border-primary pl-8">
                        "In an efficient market, you buy the haystack. In an inefficient market, you find the needles."
                    </p>

                    <h2 className="text-3xl font-serif font-bold text-slate-900 mt-16 mb-8">Introduction: The Western Bias</h2>
                    <p>
                        The push toward "Passive Investing" (Index Funds/ETFs) is largely a trend imported from the United States. In the US, where trillions of dollars in high-frequency trading ensure that any new information is priced in within milliseconds, beating the index is mathematically difficult.
                    </p>
                    <p>
                        However, the <strong>Indian market is fundamentally different</strong>. India is an "Information Asymmetric" market. Deep on-ground research, management interaction, and sectoral specialization still provide a massive edge. For an HNI with ₹50L+, settling for the index means missing out on the <strong>Alpha</strong> generated by India’s structural industrialization. This guide explores why active management remains the superior choice for Indian wealth.
                    </p>

                    <h2 className="text-3xl font-serif font-bold text-slate-900 mt-16 mb-8">Concept Explained: Why Indexes Underperform in India</h2>
                    <p>
                        An Index (like Nifty 50) is a <strong>Rear-View Mirror</strong>. It is constructed based on past performanceinvesting the most capital in yesterday's winners.
                    </p>
                    <div className="my-12 p-8 bg-slate-50 rounded-3xl border border-slate-200">
                        <h4 className="text-xl font-bold text-slate-900 mb-4">The Inefficiencies of an Index:</h4>
                        <ul className="space-y-4">
                            <li><strong>Consensus Weightage:</strong> Indexes are forced to buy more of a stock when it’s expensive (high market cap) and sell it when it’s cheap (low market cap). This is the opposite of value investing.</li>
                            <li><strong>Sector Concentration:</strong> The Nifty is often heavily tilted toward a few sectors (like BFSI or IT). Passive investors are unknowingly making massive sectoral bets.</li>
                            <li><strong>Missing the SME Boom:</strong> The greatest wealth creators in India often start in the small and mid-cap spaces, which are excluded from the main indexes until they have already grown 10x.</li>
                        </ul>
                    </div>

                    <h2 className="text-3xl font-serif font-bold text-slate-900 mt-16 mb-8">Strategic Importance for India's ₹1Cr+ Portfolios</h2>
                    <div className="grid md:grid-cols-2 gap-8 my-12">
                        <div className="bg-white p-8 rounded-2xl border border-slate-200 shadow-sm">
                            < SearchCheck className="text-primary mb-4" size={32} />
                            <h4 className="text-xl font-bold text-slate-900 mb-2">Management Forensics</h4>
                            <p className="text-base text-slate-600">Active managers can filter out companies with poor governancesomething an index cannot do. In India, avoiding "Governance Gaps" is the easiest way to generate 2-3% of Alpha.</p>
                        </div>
                        <div className="bg-white p-8 rounded-2xl border border-slate-200 shadow-sm">
                            < Trophy className="text-primary mb-4" size={32} />
                            <h4 className="text-xl font-bold text-slate-900 mb-2">Sector Rotation</h4>
                            <p className="text-base text-slate-600">Active managers can pivot capital from expensive consumer tech to undervalued industrials. An index is stuck with its weightings for months.</p>
                        </div>
                    </div>

                    <h2 className="text-3xl font-serif font-bold text-slate-900 mt-16 mb-8">Practical Application: Identifying Quality Alpha</h2>

                    <div className="space-y-12 my-12">
                        <div className="border border-slate-200 rounded-3xl p-8 shadow-sm">
                            <h3 className="text-2xl font-bold text-slate-900 mb-4 flex items-center gap-3">
                                <span className="text-primary">Scenario:</span> The Rise of the "China+1" Sector
                            </h3>
                            <p><strong>Indexing:</strong> You own the large-cap chemical companies that are already fully priced. <br /><strong>Active Alpha:</strong> We identify the niche component makers with 500Cr market cap that are currently winning contracts from global OEMs. These are the future 10x multibaggers that won't enter the index for another 5 years.</p>
                        </div>

                        <div className="border border-slate-200 rounded-3xl p-8 shadow-sm bg-orange-50/50 border-none relative overflow-hidden">
                            <h3 className="text-2xl font-bold mb-4 flex items-center gap-3 text-slate-900">
                                <span className="text-primary">Scenario:</span> The "Safety" of a Low-Cost Nifty Fund
                            </h3>
                            <p className="text-slate-700"><strong>Reality check:</strong> While you save 0.5% in fees, you might be forfeiting 5% in potential Alpha. For a ₹5Cr portfolio, that 5% is ₹25 Lakhs per year. The "saving" becomes a massive loss.</p>
                        </div>
                    </div>

                    <h2 className="text-3xl font-serif font-bold text-slate-900 mt-16 mb-8">What sophisticated investors get wrong</h2>
                    <ul className="space-y-4">
                        <li><strong>Assuming Alpha is Constant:</strong> Active management is not about beating the market every quarter; it’s about beating it over a 3-5 year cycle.</li>
                        <li><strong>Underestimating Governance Risk:</strong> Thinking that "being in the index" makes a stock safe. History shows that even index companies can have massive governance failures.</li>
                        <li><strong>Ignoring Tracking Error:</strong> Believing that an index fund perfectly replicates the market. In reality, impact costs and rebalancing delays in India can lead to significant 'slippage' even in passive funds.</li>
                    </ul>

                    <h2 className="text-3xl font-serif font-bold text-slate-900 mt-16 mb-8">Advisor’s Perspective</h2>
                    <p>
                        At Tiger Assets, our mandate is <strong>High-Conviction Alpha</strong>. We utilize the <strong>TIGER Framework</strong> to find the companies that are mispriced by the broader market. We don't hide behind a benchmark; we seek absolute returns by identifying emerging hegemonies before the index captures them. For an HNI in India, <strong>active management is not a luxury; it is a statistical necessity for wealth outperformance.</strong>
                    </p>

                    <div className="bg-slate-950 p-10 rounded-[40px] text-white my-16 relative overflow-hidden">
                        <div className="absolute top-0 left-0 w-96 h-96 bg-primary/10 rounded-full blur-[100px]"></div>
                        <h3 className="text-2xl font-bold mb-6 flex items-center gap-3 text-white">
                            < TrendingUp className="text-primary" />
                            Alpha Opportunity Audit
                        </h3>
                        <ul className="space-y-6">
                            <li className="flex gap-4">
                                <div className="bg-white/10 w-8 h-8 rounded-full border border-white/20 flex items-center justify-center font-bold text-primary shrink-0">1</div>
                                <span className="text-slate-300">Are you missing the <strong>SME Industrial Revolution</strong> because your funds only track the Nifty 50?</span>
                            </li>
                            <li className="flex gap-4">
                                <div className="bg-white/10 w-8 h-8 rounded-full border border-white/20 flex items-center justify-center font-bold text-primary shrink-0">2</div>
                                <span className="text-slate-300">Does your advisor conduct <strong>direct management interactions</strong> before making an allocation?</span>
                            </li>
                            <li className="flex gap-4">
                                <div className="bg-white/10 w-8 h-8 rounded-full border border-white/20 flex items-center justify-center font-bold text-primary shrink-0">3</div>
                                <span className="text-slate-300">Are you paying 'active' fees for a portfolio that has a <strong>90% overlap</strong> with the index? (Closet Indexing).</span>
                            </li>
                        </ul>
                    </div>

                    <h2 className="text-3xl font-serif font-bold text-slate-900 mt-16 mb-8 flex items-center gap-3">
                        <HelpCircle className="text-primary" size={32} />
                        Frequently Asked Questions
                    </h2>
                    <div className="space-y-8 divide-y divide-slate-100">
                        <div className="pt-8">
                            <h4 className="text-lg font-bold text-slate-900 mb-3">Doesn't the data say most active funds underperform?</h4>
                            <p className="text-slate-600">In the US, yes. In India, 'Large Cap' mutual funds struggle, but PMS and SME mandates consistently generate deep Alpha. We don't recommend generic mutual funds; we recommend specialized active mandates.</p>
                        </div>
                        <div className="pt-8">
                            <h4 className="text-lg font-bold text-slate-900 mb-3">Can I combine indexing and active management?</h4>
                            <p className="text-slate-600">Yes. Use indexing for your debt or large-cap exposure, but reserve your "Growth Capital" for active, high-conviction strategies where research adds the most value.</p>
                        </div>
                    </div>
                </div>

                {/* Internal Links CTA */}
                <div className="mt-20 p-12 bg-slate-50 rounded-3xl border border-slate-200 text-center relative">
                    <h3 className="text-2xl font-bold text-slate-900 mb-4">Find the needles. Build the future.</h3>
                    <p className="text-slate-600 mb-8 max-w-2xl mx-auto">Explore how our high-conviction PMS strategies have consistently outperformed benchmarks through deep on-ground research.</p>
                    <div className="flex flex-wrap justify-center gap-4">
                        <Link href="/products/sre-tiger-pms">
                            <button className="bg-primary text-white px-10 py-4 rounded-full font-bold hover:shadow-2xl transition-all">SRE Tiger PMS Strategy</button>
                        </Link>
                        <Link href="/framework">
                            <button className="bg-white text-slate-900 border border-slate-200 px-10 py-4 rounded-full font-bold hover:bg-slate-50 transition-all font-serif">Our TIGER Framework</button>
                        </Link>
                    </div>
                </div>
            </article>

            <Footer />
        </main>
    );
}
